### ISSUE TITLE
How do you pre-process the Robotcar dataset

### ISSUE THREAD

**Issue by goxq** [ucaszyp/STEPS#1]
Thanks for your excellent work! 

Since the image in the robotcar dataset is distorted(and in a gray tone) and is in a full-size, I wonder how you specifically pre-process the images in this dataset?

**Comment by ucaszyp** [comment]
Thanks for your interests!We use the offical python sdk (https://github.com/ori-mrg/robotcar-dataset-sdk)

**Comment by ucaszyp** [comment]
Thanks for your interests! We use the offical python sdk (https://github.com/ori-mrg/robotcar-dataset-sdk)

**Comment by ucaszyp** [comment]
Thanks for your interests! 
We use the official python-sdk of RobotCar (https://github.com/ori-mrg/robotcar-dataset-sdk), which provides project_laser_into_image, demosaic and undistort function. You can easily find them in project_laser_into_camer.py and image.py. Args we used are shown in the following figure. Under this setting, input Bayer images transformed to RGB by demasaicing function(image.py line 46) and then undistorted(image.py line 48). Finally, pointcloud is projected into the image (project_laser_into_camer.py)
Note that, the number of LiDAR points in one frame is  small, so the official python-sdk combines multiple frames to generate ground truth depth based on Structure-from-Motion. Moving objects lead to wrong outputs. Therefore, the previous works manually select scenes without moving objects.
![args](https://user-images.githubusercontent.com/61369578/216590317-aef6cd83-cbd5-47f4-877e-bbd422b8cfcb.PNG)

**Comment by ucaszyp** [comment]
> Thanks for your excellent work!
> 
> Since the image in the robotcar dataset is distorted(and in a gray tone) and is in a full-size, I wonder how you specifically pre-process the images in this dataset?



> Thanks for your excellent work!
> 
> Since the image in the robotcar dataset is distorted(and in a gray tone) and is in a full-size, I wonder how you specifically pre-process the images in this dataset?

Thanks for your interests! 
We use the official python-sdk of RobotCar (https://github.com/ori-mrg/robotcar-dataset-sdk), which provides project_laser_into_image, demosaic and undistort function. You can easily find them in project_laser_into_camer.py and image.py. Args we used are shown in the following figure. Under this setting, input Bayer images are transformed to RGB by demasaicing function(image.py line 46) and then undistorted(image.py line 48). Finally, pointcloud is projected into the image (project_laser_into_camer.py)
Note that, the number of LiDAR points in one frame is  small, so the official python-sdk combines multiple frames to generate ground truth depth based on Structure-from-Motion. Moving objects lead to wrong outputs. Therefore, the previous works manually select scenes without moving objects.
![args](https://user-images.githubusercontent.com/61369578/216591291-8616fcf7-98f0-432d-804b-3dfdfc0994b3.PNG)

**Comment by goxq** [comment]
@ucaszyp 
Thank you so much for the very helpful information!!!

So the conversion and undistorted of the images is done in advance (results are placed in the 'rgb' folder) and the cropping and resizing of the images is done when the dataset is loaded (in the code), is that correct?

I'd also like to confirm what the value of 'intrinsic.npy' is in the robot car dataset.

Thx!!

**Comment by ucaszyp** [comment]
> @ucaszyp Thank you so much for the very helpful information!!!
> 
> So the conversion and undistorted of the images is done in advance (results are placed in the 'rgb' folder) and the cropping and resizing of the images is done when the dataset is loaded (in the code), is that correct?
> 
> I'd also like to confirm what the value of 'intrinsic.npy' is in the robot car dataset.
> 
> Thx!!

Absolutely correct. In fact, the values in intrinsic.npy are officially provided by robotcar python-sdk. When we crop and resize the images, intrinsic is also processed in the same way. (You can easily find these in dataset/robotcar.py(nuscenes.py) *_with_intrinsic)

**Comment by goxq** [comment]
Thx!!
